apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-app-verifier
---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-verifier
  labels:
    app: voting-app-verifier
spec:
  serviceAccountName: voting-app-verifier
  containers:
    - name: verifier
      image: mikesir87/voting-app-verifier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voting-app-verifier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: voting-app-verifier
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-verifier
spec:
  type: NodePort
  selector:
    app: voting-app-verifier
  ports:
    - port: 3000