apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
  labels:
    app: readiness-proeb
spec:
  containers:
  - name: restarting-app
    image: mikeisr87/cs2304-k8s:restarting-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    readinessProbe:
      httpGet:
        path: /fix-the-spelling.html
        port: 80
      periodSeconds: 3
      failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-probe
spec:
  selector:
    app: readiness-probe
  ports:
    - port: 80
      targetPort: 80
