apiVersion: v1
kind: Pod
metadata:
  name: pod-from-remote-manifest
  labels:
    app: cats
spec:
  containers:
    - name: app
      image: mikesir87/cats:1.0
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: remote-manifest
spec:
  selector:
    app: cats
  ports:
    - port: 5000
      targetPort: 5000
