apiVersion: v1
kind: Namespace
metadata:
  name: cs2304-final-missing-endpoints
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: cs2304-final-missing-endpoints
  labels:
    app: nginx-app
spec:
  containers:
  - name: app
    image: nginx:alpine
    readinessProbe:
      httpGet:
        path: /
        port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cs2304-final-missing-endpoints
spec:
  selector:
    app: nginx
  ports:
    - port: 80