apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-verifier
---
apiVersion: v1
kind: Pod
metadata:
  name: ingress-verifier
  labels:
    app: ingress-verifier
spec:
  serviceAccountName: ingress-verifier
  containers:
    - name: verifier
      image: mikesir87/cs2304-verifier:ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-verifier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: ingress-verifier
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-verifier
spec:
  type: ClusterIP
  selector:
    app: ingress-verifier
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-verifier
spec:
  rules:
    - host: verifier.local.mikesir87.training
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-verifier
                port:
                  number: 3000